### ISSUE TITLE
How is this working?

### ISSUE THREAD

**Issue by frankie71** [Timvissers/tafeltennis-klassementen-be#4]
Hi Tim,

This looks promising, but I am trying to figure out how this code is working in either excel of google sheets, can you explain a bit please?

Thanks,

**Comment by Timvissers** [comment]
Hello,

I added an example of my usage in Google spreadsheets: https://github.com/Timvissers/tafeltennis-klassementen-be/blob/master/USAGE.md

There is no automation, it is a bunch of manual steps. But that works fine enough for me, as the setup is a one-time task for my individual usage.

If needed, I can try to share a Google spreadsheet so that all spreadsheet formula's for my usage are there. So it can be reused.

Grts,

**Comment by Timvissers** [comment]
Here is a stripped down example: https://docs.google.com/spreadsheets/d/1xbHsJZ8x_bdYKzffOnV8ehwgzmrxlgThdnLUAx0HaE4/edit?usp=sharing
